{{- if .Values.stackdriverZipkin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-zipkin
spec:
  type: ClusterIP
  ports:
  - port: 9411
    targetPort: 9411
  selector:
    app: {{ template "fullname" . }}-zipkin
---
{{- end }}