dependencies:
- name: kube-lego
  version: 0.1.10
  condition: kube-lego.enabled
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: spinnaker
  version: 0.3.2
  condition: spinnaker.enabled
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: istio
  version: 0.2.7-chart6
  condition: istio.enabled
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
- name: nginx-ingress
  version: 0.8.11
  condition: nginx-ingress.enabled
  repository: https://kubernetes-charts.storage.googleapis.com/
