dependencies:
- name: kube-lego
  version: 0.1.10
  condition: kube-lego.enabled
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: prometheus
  version: 3.0.2
  condition: prometheus.enabled
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: spinnaker
  version: 0.2.0
  condition: spinnaker.enabled
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: istio
  version: 0.2.1
  condition: istio.enabled
  repository: http://storage.googleapis.com/kubernetes-charts-incubator/
- name: nginx-ingress
  version: 0.6.0
  condition: nginx-ingress.enabled
  repository: https://kubernetes-charts.storage.googleapis.com/