dependencies:
- name: kube-lego
  version: 0.1.10
  condition: kube-lego.enabled
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: spinnaker
  version: 0.3.2
  condition: spinnaker.enabled
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: istio
  version: 0.2.6-chart5
  condition: istio.enabled
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
- name: gitlab
  version: 0.1.6
  condition: gitlab.enabled
  repository: https://charts.gitlab.io/
- name: nginx-ingress
  version: 0.8.1
  condition: nginx-ingress.enabled
  repository: https://kubernetes-charts.storage.googleapis.com/