# Default values for gke-helper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
project: vic-goog

prometheus:
  enabled: true

grafana:
  enabled: true
  serviceType: ClusterIP
  adminUser: admin
# Override this to set a particular password, otherwise a random string is generated
# adminPassowrd: supersecret
  persistentVolume:
    size: 10Gi
    subpath: ""
  image:
    repo: grafana/grafana
    tag: 4.3.2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 100Mi

ingress:
  enabled: true
  httpHostSubDomain: k8s.dev.vicnastea.io
  class: nginx

externalDns:
  enabled: true
  image:
    repository: registry.opensource.zalan.do/teapot/external-dns
    tag: v0.3.0
  sources:
    - service
    - ingress
  #will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
  #domainFilter: myDomain.example.com
  # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
  policy: upsert-only
  registry: txt
  txtOwnerId: my-identifier

nginx-ingress:
  enabled: true
  controller:
    publishService:
      enabled: true

kube-lego:
  enabled: true
  config:
    LEGO_EMAIL: viglesias@google.com
    LEGO_URL: https://acme-v01.api.letsencrypt.org/directory
    LEGO_SECRET_NAME: lego-acme-production

spinnaker:
  enabled: false

istio:
  enabled: false
  rbac:
    install: true

stackdriverZipkin:
  enabled: false
  image:
    repository: gcr.io/stackdriver-trace-docker/zipkin-collector
    tag: latest
  addons:
    zipkin:
      enabled: false
    prometheus:
      enabled: false

gitlab:
  enabled: false
  serviceType: ClusterIP
  gitlabRootPassword: gke-toolbox
  externalUrl: http://gitlab.k8s.dev.vicnastea.io