{{- if .Values.grafana.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ .Chart.Name }}
    component: grafana
  name: {{ template "fullname" . }}-grafana-datasource
  annotations:
   "helm.sh/hook": post-install
   "helm.sh/hook-weight": "1"
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: grafana
    spec:
      containers:
      - name: {{ template "fullname" . }}-grafana-datasource
        image: appropriate/curl:latest
        env:
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-grafana
              key: grafana-admin-user
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-grafana
              key: grafana-admin-password
        args:
          - "http://$(ADMIN_USER):$(ADMIN_PASSWORD)@{{ .Release.Name }}-grafana/api/datasources"
          - "-X"
          - POST
          - "--max-time"
          - "10"
          - "-H"
          - "Content-Type: application/json;charset=UTF-8"
          - "--data-binary"
          - "{\"name\":\"Prometheus\",\"type\":\"prometheus\",\"url\":\"http://prometheus-operated:9090\",\"access\":\"proxy\",\"isDefault\":true}"
      restartPolicy: OnFailure
{{- end -}}