{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install
  labels:
    app: {{ .Release.Name }}
    component: grafana
  name: {{ .Release.Name }}-grafana
type: Opaque
data:
  {{- if .Values.grafana.adminPassword }}
  grafana-admin-password: {{ .Values.grafana.adminPassword | b64enc | quote }}
  {{- else }}
  grafana-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  grafana-admin-user: {{ .Values.grafana.adminUser | default "admin" | b64enc | quote }}
{{- end -}}

