{{- if .Values.istio.enabled }}
{{- $serviceName := include "istio.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ include "istio.name" . }}
    component: istio
data:
  mesh: |-
{{ if .Values.istio.auth.enabled }}
    authPolicy: MUTUAL_TLS
{{ end }}
    # Set the following variable to true to disable policy checks by the Mixer.
    # Note that metrics will still be reported to the Mixer.
    disablePolicyChecks: false
    # Set enableTracing to false to disable request tracing.
    {{- if .Values.stackdriverZipkin.enabled }}
    enableTracing: true
    {{- else }}
    enableTracing: false
    {{- end }}
    #
    # To disable the mixer completely (including metrics), comment out
    # the following line
    defaultConfig:
      # See rdsRefreshDelay for explanation about this setting.
      discoveryRefreshDelay: 1s
      #
      # TCP connection timeout between Envoy & the application, and between Envoys.
      connectTimeout: 10s
      #
      ### ADVANCED SETTINGS #############
      # Where should envoy's configuration be stored in the istio-proxy container
      configPath: "/etc/istio/proxy"
      binaryPath: "/usr/local/bin/envoy"
      # The pseudo service name used for Envoy.
      serviceCluster: istio-proxy
      # These settings that determine how long an old Envoy
      # process should be kept alive after an occasional reload.
      drainDuration: 45s
      parentShutdownDuration: 1m0s
      proxyAdminPort: 15000
      mixerAddress: istio-mixer:9091
      discoveryAddress: {{ $serviceName }}-{{ .Values.istio.pilot.name }}.{{ .Release.Namespace }}:{{ .Values.istio.pilot.service.externalHttpDiscovery }}
      zipkinAddress: istio-{{ .Values.istio.addons.zipkin.deployment.name }}.{{ .Release.Namespace }}:9411
      discoveryAddress: {{ $serviceName }}-{{ .Values.istio.pilot.name }}.{{ .Release.Namespace }}:{{ .Values.istio.pilot.service.externalHttpDiscovery }}
{{- end }}