{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
  {{- if .Values.ingress.sslEnabled }}
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
  {{- end }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
{{- if .Values.ingress.sslEnabled }}
  tls:
  {{- if .Values.grafana.enabled }}
  - hosts:
    - grafana.{{required "You must set `ingress.httpHostSubDomain` in the values file" .Values.ingress.httpHostSubDomain }}
    secretName: {{ template "fullname" . }}-grafana
  {{- end }} 
{{- end }}
  rules:
  {{- if .Values.grafana.enabled }}
  - host: grafana.{{required "You must set `ingress.httpHostSubDomain` in the values file" .Values.ingress.httpHostSubDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-grafana
          servicePort: 80
  {{- end }}
{{- end }}
