{{- if .Values.test.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-nginx
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - {{ .Values.test.httpHost }}
    secretName: {{ template "fullname" . }}-nginx-tls
  rules:
  - host: {{ .Values.test.httpHost }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ template "fullname" . }}-nginx
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.test.tcpHost }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ template "fullname" . }}-nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-nginx
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-nginx
    spec:
      containers:
      - image: nginx:stable
        name: nginx
        ports:
        - containerPort: 80
---
{{- end }}