{{- if .Values.externalDns.enabled }}
{{ required "You must set `project` in the values file" .Values.project }}
{{ $kubeLegoValues := index .Values "kube-lego" }}
{{- if $kubeLegoValues.enabled }}
  {{ $kubeLegoEmail := $kubeLegoValues.config.LEGO_EMAIL  }}
  {{ required "You must set `kube-lego.config.LEGO_EMAIL` in the values file" $kubeLegoEmail }}
{{- end }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-external-dns
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: external-dns
        image: {{ .Values.externalDns.image.repository }}:{{ .Values.externalDns.image.tag }}
        args:
        {{- range $index, $value := .Values.externalDns.sources }}
        - --source={{ $value }}
        {{- end }}
        {{- if .Values.externalDns.domainFilter }}
        - --domain-filter={{ .Values.externalDns.image.repository }} 
        {{- end }}
        - --provider=google
        - --google-project={{ .Values.project }}
        - --policy={{ .Values.externalDns.policy }}
        - --registry={{ .Values.externalDns.registry }}
        - --txt-owner-id={{ .Values.externalDns.txtOwnerId }}
{{- end }}