{{- if .Values.prometheus.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: istio
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    prometheus: {{ .Release.Name }}
  name: istio-mixer
spec:
  jobLabel: {{ template "fullname" . }}
  selector:
    matchLabels:
      istio: istio-mixer
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: statsd-prom
    interval: 15s
    scheme: http
  - port: prometheus
    interval: 15s
    scheme: http
{{- end -}}